import { Mail, MessageCircle, Phone, Instagram } from "lucide-react";
import { FormEvent, useState } from "react";
import { businessConfig } from "../data/config";
import { createWhatsAppUrl } from "../utils/whatsapp";
import { usePageMeta } from "../utils/usePageMeta";

export function Contact() {
  usePageMeta("Contact | Fragrances by D'Ruaa", "Contact Fragrances by D'Ruaa for product enquiries.");
  const [form, setForm] = useState({ name: "", phone: "", email: "", product: "", message: "" });
  const submit = (event: FormEvent) => { event.preventDefault(); const message = `Hi, I would like to enquire about Fragrances by D'Ruaa.\n\nName: ${form.name}\nPhone/WhatsApp: ${form.phone}\nEmail: ${form.email}\nProduct of interest: ${form.product}\nMessage: ${form.message}`; window.open(createWhatsAppUrl(message), "_blank", "noopener,noreferrer"); };
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  return <main className="container-px section-y"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.85fr_1.15fr]"><div><p className="eyebrow">Contact</p><h1 className="mt-4 font-display text-6xl font-semibold leading-none">Let's Talk Fragrance</h1><p className="mt-6 text-base leading-8 text-muted">Looking for a particular fragrance, product, or need help choosing? Get in touch with us.</p><div className="mt-8 grid gap-4 text-sm"><a className="flex items-center gap-3" href={`https://wa.me/${businessConfig.whatsappNumber}`}><MessageCircle size={18} /> WhatsApp</a><a className="flex items-center gap-3" href={`tel:${businessConfig.phone.replace(/\s/g, "")}`}><Phone size={18} /> {businessConfig.phone}</a><a className="flex items-center gap-3" href={`mailto:${businessConfig.email}`}><Mail size={18} /> {businessConfig.email}</a><a className="flex items-center gap-3" href={businessConfig.instagramUrl}><Instagram size={18} /> Instagram</a></div></div><form onSubmit={submit} className="grid gap-5 border border-border bg-cream/55 p-6 sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><input required placeholder="Name" value={form.name} onChange={(e) => update("name", e.target.value)} className="border border-border bg-white/70 p-4" /><input required placeholder="Phone / WhatsApp" value={form.phone} onChange={(e) => update("phone", e.target.value)} className="border border-border bg-white/70 p-4" /></div><input type="email" placeholder="Email" value={form.email} onChange={(e) => update("email", e.target.value)} className="border border-border bg-white/70 p-4" /><input placeholder="Product of Interest" value={form.product} onChange={(e) => update("product", e.target.value)} className="border border-border bg-white/70 p-4" /><textarea required placeholder="Message" rows={6} value={form.message} onChange={(e) => update("message", e.target.value)} className="border border-border bg-white/70 p-4" /><button className="bg-charcoal px-6 py-4 text-sm font-semibold text-ivory" type="submit">Create WhatsApp Enquiry</button><p className="text-xs leading-6 text-muted">This form opens a WhatsApp message on your device. It does not store submissions.</p></form></div></main>;
}
